ALTER TABLE budgets
  ADD COLUMN raw_material_cost NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN overhead_cost NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN profit_margin NUMERIC(5,2) NOT NULL DEFAULT 0;
